// src/stores/furnitureStore.js

import { defineStore } from 'pinia';

export const useFurnitureStore = defineStore('furnitureStore', {
  state: () => ({
    // Fix camera picture (check HabboX wiki)
    // extract camera store banner from HabboX wiki
    // extract HC category image
    // extract teleporter category image
    categories: [
        { name: 'Accessories', image: '../src/assets/categories/accessories.gif', thumbnail: '../src/assets/fansite/catalog_icons/accessories.png'},
        { name: 'Area', image: '../src/assets/categories/area.gif', thumbnail: '../src/assets/fansite/catalog_icons/area.png'},
        { name: 'Bathroom', image: '../src/assets/categories/bathroom.gif', thumbnail: '../src/assets/fansite/catalog_icons/bath.png'},
        { name: 'Candy', image: '../src/assets/categories/candy.gif', thumbnail: '../src/assets/fansite/catalog_icons/candy.png'},
        { name: 'Flags', image: '../src/assets/categories/flags.gif', thumbnail: '../src/assets/fansite/catalog_icons/flags.png'},
        { name: 'Lodge', image: '../src/assets/categories/lodge.gif', thumbnail: '../src/assets/fansite/catalog_icons/lodge.png'},
        { name: 'Gallery', image: '../src/assets/categories/gallery.gif', thumbnail: '../src/assets/fansite/catalog_icons/gallery.png'},
        { name: 'Iced', image: '../src/assets/categories/iced.gif', thumbnail: '../src/assets/fansite/catalog_icons/iced.png'},
        { name: 'Mode', image: '../src/assets/categories/mode.gif', thumbnail: '../src/assets/fansite/catalog_icons/mode.png'},
        { name: 'Pets', image: '../src/assets/categories/pet_acc.gif', thumbnail: '../src/assets/fansite/catalog_icons/pets.png'},
        { name: 'Plants', image: '../src/assets/categories/plants.gif', thumbnail: '../src/assets/fansite/catalog_icons/plants.png'},
        { name: 'Plasto', image: '../src/assets/categories/plastic.gif', thumbnail: '../src/assets/fansite/catalog_icons/plasto.png'},
        //{ name: 'Presents', image: '../src/assets/categories/Presents.png', thumbnail: '../src/assets/fansite/catalog_icons/gift.png'},
        { name: 'Pura', image: '../src/assets/categories/pura.gif', thumbnail: '../src/assets/fansite/catalog_icons/pura.png'},
        { name: 'Rares', image: '../src/assets/categories/rares.gif', thumbnail: '../src/assets/fansite/catalog_icons/rares.png'},
        { name: 'Rollers', image: '../src/assets/categories/Rollers.png', thumbnail: '../src/assets/fansite/catalog_icons/rollers.png'},
        { name: 'Rugs', image: '../src/assets/categories/rugs.gif', thumbnail: '../src/assets/fansite/catalog_icons/rugs.png'},
        { name: 'Teleport', image: '../src/assets/categories/Teleports.gif', thumbnail: '../src/assets/fansite/catalog_icons/teleports.png'},
        { name: 'Trophies', image: '../src/assets/categories/Trophhead.gif', thumbnail: '../src/assets/fansite/catalog_icons/trophies.png'},
        { name: 'Camera', image: '../src/assets/categories/camera.png', thumbnail: '../src/assets/fansite/catalog_icons/camera.png'},
        { name: 'HC', image: '../src/assets/categories/hc.gif', thumbnail: '../src/assets/fansite/catalog_icons/hc.png'},
    ],

    items: [
        // Add presents.

        { name: 'Habbo Cola Machine', category: 'Rares', credits: 50, image: '../src/assets/furni/rares/cola.gif' },
        { name: 'Petal Patch', category: 'Rares', credits: 30, image: '../src/assets/furni/rares/petal.gif' },

        { name: 'Single Bed', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_bed_1.gif' },
        { name: 'Double Bed', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_bed_2.gif' },
        { name: 'Dining Chair', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_chair.gif' },
        { name: 'Corner Shelf', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_corner.gif' },
        { name: 'Screen', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_divider.gif' },
        { name: 'Gate (lockable)', category: 'Area', credits: 6, image: '../src/assets/furni/area/area_gate.gif' },
        { name: 'Bookcase', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_bookshelves.gif' }, 
        { name: 'Armchair', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_armchair.gif' },
        { name: 'Two-Seater Sofa', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_sofa.gif' },
        { name: 'Coffee Table', category: 'Area', credits: 3, image: '../src/assets/furni/area/area_coffeetable.gif' },
        { name: 'Occasional Table', category: 'Area', credits: 1, image: '../src/assets/furni/area/area_table.gif' }, 

        { name: 'Single Bed', category: 'Candy', credits: 3, image: '../src/assets/furni/candy/mode_bed_1_pink.gif' },
        { name: 'Armchair', category: 'Candy', credits: 3, image: '../src/assets/furni/candy/mode_chair_pink.gif' },
        { name: 'Double Bed', category: 'Candy', credits: 4, image: '../src/assets/furni/candy/mode_bed_2_pink.gif' },
        { name: 'Two-seater Sofa', category: 'Candy', credits: 4, image: '../src/assets/furni/candy/mode_sofa_pink.gif' },
        { name: 'Pink Faux-Fur Bear Rug', category: 'Candy', credits: 4, image: '../src/assets/furni/candy/bear_rug_pink.gif' },

        { name: 'Chair', category: 'Iced', credits: 3, image: '../src/assets/furni/iced/iced_1.gif' },
        { name: 'Bench', category: 'Iced', credits: 3, image: '../src/assets/furni/iced/iced_2.gif' },
        { name: 'Ice Corner', category: 'Iced', credits: 3, image: '../src/assets/furni/iced/iced_8.gif' },
        { name: 'Ice Bar-Desk', category: 'Iced', credits: 3, image: '../src/assets/furni/iced/iced_7.gif' },
        { name: 'Door (Lockable)', category: 'Iced', credits: 6, image: '../src/assets/furni/iced/iced_9.gif'   },
        { name: 'Bookcase', category: 'Iced', credits: 3, image: '../src/assets/furni/iced/iced_4.gif'},
        { name: 'Large Dining Table', category: 'Iced', credits: 4, image: '../src/assets/furni/iced/mode_table_5.gif' },
        { name: 'iced sofachair', category: 'Iced', credits: 3, image: '../src/assets/furni/iced/iced_5.gif' },
        { name: 'iced sofa', category: 'Iced', credits: 4, image: '../src/assets/furni/iced/iced_6.gif' },

        { name: 'Lodge Candle', category: 'Lodge', credits: 5, image: '../src/assets/furni/lodge/lodge_candle.gif' },
        { name: 'Single Bed', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_bed_1.gif' },
        { name: 'Double Bed', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_bed_2.gif' },
        { name: 'Dining Table', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_table_1.gif' },
        { name: 'Occasional Table', category: 'Lodge', credits: 2, image: '../src/assets/furni/lodge/lodge_table_2.gif' },
        { name: 'Bench', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_bench.gif' },
        { name: 'Stool', category: 'Lodge', credits: 1, image: '../src/assets/furni/lodge/lodge_stool.gif' },
        { name: 'Barrel Stool', category: 'Lodge', credits: 1, image: '../src/assets/furni/lodge/lodge_barrel.gif' },
        { name: 'Bookcase', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_bookshelf.gif' },
        { name: 'Table Lamp', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_table_2.gif' },
        { name: 'Barrel Minibar', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_minibar.gif' },
        { name: 'Corner plinth', category: 'Lodge', credits: 4, image: '../src/assets/furni/lodge/lodge_corner.gif' },
        { name: 'Fireplace', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_fireplace.gif' },
        { name: 'Bardesk', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_bardesk.gif' },
        { name: 'Room divider', category: 'Lodge', credits: 3, image: '../src/assets/furni/lodge/lodge_divider.gif' },

        { name: 'Armchair', category: 'Mode', credits: 3, image: '../src/assets/furni/mode/mode_chair.gif' },
        { name: 'Single Bed', category: 'Mode', credits: 3, image: '../src/assets/furni/mode/mode_bed_1.gif' },
        { name: 'Small Coffee Table', category: 'Mode', credits: 1, image: '../src/assets/furni/mode/mode_table_2.gif' },
        { name: 'Dining Chair', category: 'Mode', credits: 3, image: '../src/assets/furni/mode/mode_tablechair.gif' },
        { name: 'Two-seater Sofa', category: 'Mode', credits: 4, image: '../src/assets/furni/mode/mode_sofa.gif' },
        { name: 'Double Bed', category: 'Mode', credits: 4, image: '../src/assets/furni/mode/mode_bed_2.gif' },
        { name: 'Large Coffee Table', category: 'Mode', credits: 3, image: '../src/assets/furni/mode/mode_table_3.gif' },
        { name: 'Shelf', category: 'Mode', credits: 1, image: '../src/assets/furni/mode/mode_table_1.gif' },
        { name: 'Bar/desk', category: 'Mode', credits: 3, image: '../src/assets/furni/mode/mode_bar.gif' },

        { name: 'Chair (White)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_white.gif' },
        { name: 'Plastic Pod Chair (White)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_white.gif' },
        { name: 'Occasional Table (White)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_white.gif' },
        { name: 'Square Dining Table (White)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_white.gif' },
        { name: 'Round Dining Table (White)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_white.gif' },
        { name: 'Occasional Table (White)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_white.gif' },
        { name: 'Chair (Aqua)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_aqua.gif' },
        { name: 'Plastic Pod Chair (Aqua)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_aqua.gif' },
        { name: 'Occasional Table (Aqua)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_aqua.gif' },
        { name: 'Square Dining Table (Aqua)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_aqua.gif' },
        { name: 'Round Dining Table (Aqua)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_aqua.gif' },
        { name: 'Occasional Table (Aqua)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_aqua.gif' },
        { name: 'Chair (Beige)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_beige.gif' },
        { name: 'Plastic Pod Chair (Beige)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_beige.gif' },
        { name: 'Occasional Table (Beige)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_beige.gif' },
        { name: 'Square Dining Table (Beige)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_beige.gif' },
        { name: 'Round Dining Table (Beige)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_beige.gif' },
        { name: 'Occasional Table (Beige)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_beige.gif' },
        { name: 'Chair (Brown)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_brown.gif' },
        { name: 'Plastic Pod Chair (Brown)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_brown.gif' },
        { name: 'Occasional Table (Brown)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_brown.gif' },
        { name: 'Square Dining Table (Brown)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_brown.gif' },
        { name: 'Round Dining Table (Brown)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_brown.gif' },
        { name: 'Occasional Table (Brown)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_brown.gif' },
        { name: 'Chair (Blue)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_blue.gif' },
        { name: 'Plastic Pod Chair (Blue)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_blue.gif' },
        { name: 'Square Dining Table (Blue)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_blue.gif' },
        { name: 'Round Dining Table (Blue)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_blue.gif' },
        { name: 'Occasional Table (Blue)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_blue.gif' },
        { name: 'Chair (green)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_green.gif' },
        { name: 'Plastic Pod Chair (green)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_green.gif' },
        { name: 'Occasional Table (green)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_green.gif' },
        { name: 'Square Dining Table (green)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_green.gif' },
        { name: 'Round Dining Table (green)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_green.gif' },
        { name: 'Occasional Table (green)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_green.gif' },
        { name: 'Chair (pink)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_pink.gif' },
        { name: 'Plastic Pod Chair (pink)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_pink.gif' },
        { name: 'Occasional Table (pink)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_pink.gif' },
        { name: 'Square Dining Table (pink)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_pink.gif' },
        { name: 'Round Dining Table (pink)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_pink.gif' },
        { name: 'Occasional Table (pink)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_pink.gif' },
        { name: 'Chair (ocean)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_ocean.gif' },
        { name: 'Plastic Pod Chair (ocean)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_ocean.gif' },
        { name: 'Occasional Table (ocean)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_ocean.gif' },
        { name: 'Square Dining Table (ocean)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_ocean.gif' },
        { name: 'Round Dining Table (ocean)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_ocean.gif' },
        { name: 'Occasional Table (ocean)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_ocean.gif' },
        { name: 'Chair (orange)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_orange.gif' },
        { name: 'Plastic Pod Chair (orange)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_orange.gif' },
        { name: 'Occasional Table (orange)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_orange.gif' },
        { name: 'Square Dining Table (orange)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_orange.gif' },
        { name: 'Round Dining Table (orange)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_orange.gif' },
        { name: 'Occasional Table (orange)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_orange.gif' },
        { name: 'Chair (purple)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_purple.gif' },
        { name: 'Plastic Pod Chair (purple)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_purple.gif' },
        { name: 'Occasional Table (purple)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_purple.gif' },
        { name: 'Square Dining Table (purple)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_purple.gif' },
        { name: 'Round Dining Table (purple)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_purple.gif' },
        { name: 'Occasional Table (purple)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_purple.gif' },
        { name: 'Chair (red)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_red.gif' },
        { name: 'Plastic Pod Chair (red)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_red.gif' },
        { name: 'Square Dining Table (red)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_red.gif' },
        { name: 'Round Dining Table (red)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_red.gif' },
        { name: 'Occasional Table (red)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_red.gif' },
        { name: 'Chair (yellow)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/chair_yellow.gif' },
        { name: 'Plastic Pod Chair (yellow)', category: 'Plasto', credits: 5, image: '../src/assets/furni/plastic/pod_yellow.gif' },
        { name: 'Occasional Table (yellow)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/rectangle_yellow.gif' },
        { name: 'Square Dining Table (yellow)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/square_yellow.gif' },
        { name: 'Round Dining Table (yellow)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/round_yellow.gif' },
        { name: 'Occasional Table (yellow)', category: 'Plasto', credits: 3, image: '../src/assets/furni/plastic/small_yellow.gif' },


        { name: 'Plain Double Bed', category: 'Pura', credits: 3, image: '../src/assets/furni/pura/pura_bed1_aqua.gif' },
        { name: 'Plain Single Bed', category: 'Pura', credits: 3, image: '../src/assets/furni/pura/pura_bed2_aqua.gif' },
        { name: 'Pura Redridgerator', category: 'Pura', credits: 6, image: '../src/assets/furni/pura/pura_fridge.gif' },
        { name: 'Pura Lamp', category: 'Pura', credits: 3, image: '../src/assets/furni/pura/pura_lamp.gif' },
        { name: 'Pura Shelves', category: 'Pura', credits: 3, image: '../src/assets/furni/pura/pura_bookshelf.gif' },      

        { name: 'Floor Tile', category: 'Bathroom', credits: 3, image: '../src/assets/furni/bathroom/tiles.gif' },
        { name: 'Bubble Bath', category: 'Bathroom', credits: 6, image: '../src/assets/furni/bathroom/bath.gif' },
        { name: 'Loo Seat', category: 'Bathroom', credits: 4, image: '../src/assets/furni/bathroom/toilet_yellow.gif' },
        { name: 'Rubber Duck', category: 'Bathroom', credits: 1, image: '../src/assets/furni/bathroom/duckie.gif' },
        { name: 'Sink', category: 'Bathroom', credits: 3, image: '../src/assets/furni/bathroom/sink.gif' },

        { name: 'Vase of Flowers', category: 'Plants', credits: 3, image: '../src/assets/furni/plants/plant_1.gif' },
        { name: 'Yukka Plant', category: 'Plants', credits: 3, image: '../src/assets/furni/plants/plant_4.gif' },
        { name: 'Mature Cactus', category: 'Plants', credits: 3, image: '../src/assets/furni/plants/plant_6.gif' },
        { name: 'Cut Sunflower', category: 'Plants', credits: 3, image: '../src/assets/furni/plants/plant_2.gif' },

        { name: 'Doormat', category: 'Rugs', credits: 1, image: '../src/assets/furni/rugs/doormat_love.gif' },
        { name: 'Doormat (Coloured)', category: 'Rugs', credits: 1, image: '../src/assets/furni/rugs/mats.gif' },
        { name: 'Soft Wool Rug (White)', category: 'Rugs', credits: 3,  image: '../src/assets/furni/rugs/rugs_2.gif' },
        { name: 'Faux-Fur Bear Rug (white)', category: 'Rugs', credits: 4, image: '../src/assets/furni/rugs/bear_rug_white.gif' },

        { name: 'Doggy Bones', category: 'Pets', credits: 1, image: '../src/assets/furni/pet/pet_food_3.gif' },
        { name: 'Sardines', category: 'Pets', credits: 1, image: '../src/assets/furni/pet/pet_food_1.gif' },
        { name: 'Cabbage', category: 'Pets', credits: 1, image: '../src/assets/furni/pet/pet_food_1.gif' },
        { name: 'Blue Water Bowl', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_drink_blue.gif' },
        { name: 'Brown Water Bowl', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_drink_brown.gif' },
        { name: 'Green Water Bowl', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_drink_green.gif' },
        { name: 'Red Water Bowl', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_drink_red.gif' },
        { name: 'Yellow Water Bowl', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_drink_yellow.gif' },
        { name: 'Rubber Ball (Red and Yellow)', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_toy_1.gif' },
        { name: 'Rubber Ball (Green and Orange)', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_toy_2.gif' },
        { name: 'Rubber Ball (Blue and Pink)', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_toy_3.gif' },
        { name: 'Rubber Ball (Cyan and Red)', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_toy_4.gif' },
        { name: 'Rubber Ball (Black and White)', category: 'Pets', credits: 2, image: '../src/assets/furni/pet/pet_toy_5.gif' },
        { name: 'Marzipan Man (Pink)', category: 'Pets', credits: 1, image: '../src/assets/furni/pet/pet_snack_1.gif' },
        { name: 'Marzipan Man (Cyan)', category: 'Pets', credits: 1, image: '../src/assets/furni/pet/pet_snack_2.gif' },
        { name: 'Marzipan Man (Yellow)', category: 'Pets', credits: 1, image: '../src/assets/furni/pet/pet_snack_3.gif' },
        { name: 'Chocolate Mouse', category: 'Pets', credits: 1, image: '../src/assets/furni/pet/pet_snack_mouse.gif' },

        { name: 'Pink Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/pink_roller.png' },
        { name: 'Red Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/red_roller.png' },
        { name: 'Purple Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/purple_roller.png' },
        { name: 'Black Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/black_roller.png' },
        { name: 'Navy Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/teal_roller.png' },
        { name: 'Green Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/green_roller.png' },
        { name: 'Gold Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/gold_roller.png' },
        { name: 'Blue Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/blue_roller.png' },
        { name: 'Aqua Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/aqua_roller.png' },
        { name: 'White Habbo Roller', category: 'Rollers', credits: 7, image: '../src/assets/furni/rollers/white_roller.png' },
        
        { name: 'Telephone Box', category: 'Teleport', credits: 5, image: '../src/assets/furni/teleport/telephone_box.gif' },
        { name: 'Portaloo', category: 'Teleport', credits: 4, image: '../src/assets/furni/teleport/portaloo.gif' },
        { name: 'Wardrobe', category: 'Teleport', credits: 3, image: '../src/assets/furni/teleport/Teleport4.png' },

        { name: 'Gold (Classic)', category: 'Trophies', credits: 12, image: '../src/assets/furni/trophies/Trophy_classicgold.png' },
        { name: 'Silver (Classic)', category: 'Trophies', credits: 10, image: '../src/assets/furni/trophies/Trophy_classicsilver.png' },
        { name: 'Bronze (Classic)', category: 'Trophies', credits: 8, image: '../src/assets/furni/trophies/Trophy_classicbronze.png' },
        { name: 'Gold (Duck)', category: 'Trophies', credits: 12, image: '../src/assets/furni/trophies/Trophy_duckgold.png' },
        { name: 'Silver (Duck)', category: 'Trophies', credits: 10, image: '../src/assets/furni/trophies/Trophy_ducksilver.png' },
        { name: 'Bronze (Duck)', category: 'Trophies', credits: 8, image: '../src/assets/furni/trophies/Trophy_duckbronze.png' },
        { name: 'Gold (Duo)', category: 'Trophies', credits: 12, image: '../src/assets/furni/trophies/Trophy_duogold.png' },
        { name: 'Silver (Duo)', category: 'Trophies', credits: 10, image: '../src/assets/furni/trophies/Trophy_duosilver.png' },
        { name: 'Bronze (Duo)', category: 'Trophies', credits: 8, image: '../src/assets/furni/trophies/Trophy_duobronze.png' },
        { name: 'Gold (Fish)', category: 'Trophies', credits: 12, image: '../src/assets/furni/trophies/Trophy_fishgold.png' },
        { name: 'Silver (Fish)', category: 'Trophies', credits: 10, image: '../src/assets/furni/trophies/Trophy_fishsilver.png' },
        { name: 'Bronze (Fish)', category: 'Trophies', credits: 8, image: '../src/assets/furni/trophies/Trophy_fishbronze.png' },
        { name: 'Gold (Solo)', category: 'Trophies', credits: 12, image: '../src/assets/furni/trophies/Trophy_sologold.png' },
        { name: 'Silver (Solo)', category: 'Trophies', credits: 10, image: '../src/assets/furni/trophies/Trophy_solosilver.png' },
        { name: 'Bronze (Solo)', category: 'Trophies', credits: 8, image: '../src/assets/furni/trophies/Trophy_solobronze.png' },
        { name: 'Gold (Sphere)', category: 'Trophies', credits: 12, image: '../src/assets/furni/trophies/Trophy_spheregold.png' },
        { name: 'Silver (Sphere)', category: 'Trophies', credits: 10, image: '../src/assets/furni/trophies/Trophy_spheresilve.png' },
        { name: 'Bronze (Sphere)', category: 'Trophies', credits: 8, image: '../src/assets/furni/trophies/Trophy_spherebronze.png' },



        { name: 'Photo', category: 'Camera', credits: 3, image: '../src/assets/furni/accessories/photo.gif' },
        { name: 'Camera', category: 'Camera', credits: 3, image: '../src/assets/furni/accessories/camera.gif' },

        { name: 'Pad of stickies', category: 'Accessories', credits: 3, image: '../src/assets/furni/accessories/sticky_1.gif' },
        { name: 'Holo-dice', category: 'Accessories', credits: 6, image: '../src/assets/furni/accessories/holo.png' },
        { name: 'Pizza Box', category: 'Accessories', credits: 3, image: '../src/assets/furni/accessories/pizzabox.png' },
        { name: 'Empty Cans', category: 'Accessories', credits: 3, image: '../src/assets/furni/accessories/cans.png' },
        { name: 'Empty Spinning Bottle', category: 'Accessories', credits: 3, image: '../src/assets/furni/accessories/spinbottle.png' },
        { name: 'Portable TV', category: 'Accessories', credits: 3, image: '../src/assets/furni/accessories/tv_2.gif' },
        { name: 'Large TV', category: 'Accessories', credits: 4, image: '../src/assets/furni/accessories/tv_3.gif' },

        { name: 'Stocking', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_1.gif' },
        { name: 'Holly Garland', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_2.gif' },
        { name: 'Carrot Plaque', category: 'Gallery', credits: 2, image: '../src/assets/furni/gallery/Gallery_n3.gif' },
        { name: 'Bear Plaque', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n5.gif' },
        { name: 'Duck Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n2.gif' },
        { name: 'Comedy Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n8.gif' },
        { name: 'Abstract Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n9.gif' },
        { name: 'Hammer Cabinet', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n12.gif' },
        { name: 'Habbo Colours', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n7.gif' },
        { name: 'Rainforest Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n10.gif' },
        { name: 'Lapland Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n11.gif' },
        { name: 'Certificate', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n13.gif' },
        { name: 'Lapland Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_2.gif' },
        { name: 'BW Skyline Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_2.gif' },
        { name: 'Fox Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n14.gif' },
        { name: 'Himalayas Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n15.gif' },
        { name: 'UK Map', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_r1.gif' },
        { name: 'Bars', category: 'Gallery', credits: 2, image: '../src/assets/furni/gallery/Gallery_n16.gif' },
        { name: 'Butterfly Cabinet 2', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n18.gif' },
        { name: 'Butterfly Cabinet', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n19.gif' },
        { name: 'Hole In The Wall', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_n17.gif' },
        { name: 'Eid Mubarak Poster', category: 'Gallery', credits: 3, image: '../src/assets/furni/gallery/Gallery_r3.gif' },


        { name: 'The Swedish flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_5.gif' },
        { name: 'The EU flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_7.gif'},
        { name: 'The Australian flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_6.gif' },
        
        { name: 'The Irish flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_8.gif' },
        { name: 'The Dutch flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_9.gif' },
        { name: 'The Italian flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_10.gif' },
        { name: 'The Jamaican flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_11.gif' },
        { name: 'The Spanish Flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_12.gif' },
        { name: 'The Bundesflagge', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_13.gif' },
        { name: 'The flag of Finland', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_1.gif' },
        { name: 'The French Tricolore', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_14.gif' },
        { name: 'The Maple Leaf', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_15.gif' },
        { name: 'The English flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_16.gif' },
        { name: 'The Rainbow Flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_17.gif' },
        { name: 'The Scottish flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_18.gif' },
        { name: 'The Welsh flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_19.gif' },
        { name: 'The Stars and Stripes', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_20.gif' },
        { name: 'The Swiss flag', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_21.gif' },
        { name: 'Union Jack', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_2.gif' },
        { name: 'Flag of Brazil', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_22.gif' },
        { name: 'Jolly Roger', category: 'Flags', credits: 3, image: '../src/assets/furni/flags/Flag_23.gif' },
 
        { name: 'Butler', category:'HC', credits: 0, image: '../src/assets/furni/hc/butler.gif' },
        { name: 'Carpet', category:'HC', credits: 0, image: '../src/assets/furni/hc/carpet.gif' },
        { name: 'Curtain', category:'HC', credits: 0, image: '../src/assets/furni/hc/curtain.gif' },
        { name: 'Chair (hc)', category: 'HC', credits: 3, image: '../src/assets/furni/plastic/chair_hc.gif' },
        { name: 'Occasional Table (hc)', category: 'HC', credits: 3, image: '../src/assets/furni/plastic/rectangle_hc.gif' },
        { name: 'Desk', category:'HC', credits: 0, image: '../src/assets/furni/hc/desk.gif' },
        { name: 'Dice', category:'HC', credits: 0, image: '../src/assets/furni/hc/dice.gif' },
        { name: 'DJ Set', category:'HC', credits: 0, image: '../src/assets/furni/hc/djset.gif' },
        { name: 'Fireplace', category:'HC', credits: 0, image: '../src/assets/furni/hc/fireplace.gif' },
        { name: 'Lamp', category:'HC', credits: 0, image: '../src/assets/furni/hc/lamp.gif' },
        { name: 'Lantern', category:'HC', credits: 0, image: '../src/assets/furni/hc/lantern.gif' },
        { name: 'Machine', category:'HC', credits: 0, image: '../src/assets/furni/hc/machine.gif' },
        { name: 'Majestic', category:'HC', credits: 0, image: '../src/assets/furni/hc/majestic.gif' },
        { name: 'Mocca', category:'HC', credits: 0, image: '../src/assets/furni/hc/mocca.gif' },
        { name: 'Nordic Chair', category:'HC', credits: 0, image: '../src/assets/furni/hc/nordic.gif' },
        { name: 'Oil Lamp', category:'HC', credits: 0, image: '../src/assets/furni/hc/oil.gif' },
        { name: 'Rollers', category:'HC', credits: 0, image: '../src/assets/furni/hc/rollers.gif' },
        { name: 'Rontgen', category:'HC', credits: 0, image: '../src/assets/furni/hc/rontgen.gif' },
        { name: 'Sofa', category:'HC', credits: 0, image: '../src/assets/furni/hc/sofa.gif' },
        { name: 'Telescope', category:'HC', credits: 0, image: '../src/assets/furni/hc/teles.gif' },
        { name: 'Throne Sofa', category:'HC', credits: 0, image: '../src/assets/furni/hc/throne_sofa.gif' },
        { name: 'Trolley', category:'HC', credits: 0, image: '../src/assets/furni/hc/trolley.gif' },
        { name: 'Tub', category:'HC', credits: 0, image: '../src/assets/furni/hc/tub.gif' },
        { name: 'TV', category:'HC', credits: 0, image: '../src/assets/furni/hc/tv.gif' }

    
    ],
  }),
  getters: {
    getItemsByCategory: (state) => (category) => {
      return state.items.filter(item => item.category === category);
    },
    getItemCategory: (state) => (itemName) => {
      const item = state.items.find(item => item.name === itemName);
      return item ? item.category : null;
    },
    getCategoryData: (state) => (catName) => {
        const category = state.categories.find(cat => cat.name === catName);
        return category ? category : null;
    }
  },
  setters: {}
});
